import Head from 'next/head';
import { FC } from 'react';
import styles from '../../styles/HomeLayout.module.css';
import { HomeLayoutProps } from '../../types/types';
import Navbar from '../organisms/Navbar';

const HomeLayout: FC<HomeLayoutProps> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </div>
  );
};

export default HomeLayout;
