import Head from 'next/head';
import { FC } from 'react';
import styles from '../../styles/components/templates/HomeLayout.module.css';
import { HomeLayoutProps } from '../../types/types';
import Graph from '../organisms/Graph';
import Navbar from '../organisms/Navbar';
import PrefectureList from '../organisms/PrefectureList';

const HomeLayout: FC<HomeLayoutProps> = ({ prefectureList, demographics }) => {
  return (
    <section className={styles.container}>
      <Head>
        <title>ゆめみコーディングテスト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h2>都道府県一覧</h2>
        <PrefectureList prefectureList={prefectureList} />
        <h2>総人口数</h2>
        <Graph demographics={demographics} />
      </main>
    </section>
  );
};

export default HomeLayout;
